import {
    faBell,
    faCamera,
    faCog,
    faEnvelope,
    faGlobeAmericas,
    faHome,
    faImage,
    faLink,
    faMusic,
    faSearch,
    faSignOutAlt,
    faUserCircle,
    faUserEdit,
    faVideo,
    faHeart as faHeartSolid,
    faAngleDoubleLeft,
    faAngleDoubleRight,
    faAngleRight,
    faAngleLeft,
} from '@fortawesome/free-solid-svg-icons'
import {
    faInstagram,
    faFacebookSquare,
    faGithubSquare,
    faTwitterSquare,
    faVk,
    faYoutube,
} from '@fortawesome/free-brands-svg-icons'
import { library } from '@fortawesome/fontawesome-svg-core'
import {
    faComment,
    faEye,
    faHeart as faHeartRegular,
    faShareSquare,
} from '@fortawesome/free-regular-svg-icons'

library.add(
    faCamera,
    faVideo,
    faImage,
    faMusic,
    faInstagram,
    faFacebookSquare,
    faGithubSquare,
    faTwitterSquare,
    faVk,
    faYoutube,
    faLink,
    faGlobeAmericas,
    faSearch,
    faHome,
    faBell,
    faEnvelope,
    faUserCircle,
    faUserEdit,
    faCog,
    faSignOutAlt,
    faHeartRegular,
    faHeartSolid,
    faEye,
    faComment,
    faShareSquare,
    faAngleDoubleLeft,
    faAngleDoubleRight,
    faAngleRight,
    faAngleLeft
)
